import { ReactNode } from 'react'
import './globals.css'
import { Nunito } from 'next/font/google'
import { BlogProvider } from './contexts/BlogContext'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'GitHub Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <BlogProvider>
        <body className={nunito.className}>{children}</body>
      </BlogProvider>
    </html>
  )
}
